// RootLayout.tsx

import type { Metadata } from "next"; // Importing the Metadata type from Next.js for type-checking the metadata object.
import { Inter } from "next/font/google"; // Importing the Inter font from Google Fonts to use in the application.
import "./globals.css"; // Importing global CSS styles for the application.

const inter = Inter({ subsets: ["latin"] }); // Creating an instance of the Inter font with Latin subsets for the application.

export const metadata: Metadata = {
  // Exporting a metadata object that provides information about the application.
  title: "Create Next App", // Title of the application, displayed in the browser tab.
  description: "Generated by create next app", // Description of the application, used for SEO and other purposes.
};

export default function RootLayout({
  // Exporting the default functional component `RootLayout`.
  children, // `children` prop that represents the nested components or content inside this layout.
}: Readonly<{
  // Using Readonly to ensure that `children` cannot be modified.
  children: React.ReactNode; // Type definition for `children` prop, specifying it as any valid React node (elements, text, etc.).
}>) {
  return (
    <html lang="en">
      {" "}
      {/* Root HTML element with language set to English. */}
      <body className={`${inter.className} custom-theme-toggle`}>
        {" "}
        {/* Body element with applied classes for font and theme. */}
        {children}{" "}
        {/* Render the nested components or content within the body. */}
      </body>
    </html>
  );
}
